[package]
name = "bindings"
version = "0.1.0"
edition = "2021"

[dependencies.windows-core]
version = "0.58.0"

[dependencies.windows]
version = "0.58.0"
features = [
    "implement",
    "Win32_System_WinRT"
]

[build-dependencies.windows-bindgen]
version = "0.58.0"