[package]
name = "bindings"
version = "0.1.0"
edition = "2021"

[dependencies.windows-core]
git = "https://github.com/riverar/windows-rs"
branch = "rafael/0.52_partialtrust"
features = [
    "implement",
]