[package]
edition = "2021"
name = "client"
version = "0.1.0"

[dependencies.bindings]
path = "../bindings"

[dependencies.windows]
git = "https://github.com/microsoft/windows-rs"
features = [
    "implement",
    "Foundation",
    "Win32_Foundation",
    "Win32_System_WinRT",
]
