[package]
edition = "2021"
name = "client"
version = "0.1.0"

[dependencies.bindings]
path = "../bindings"

[dependencies.windows]
features = [
    "implement",
    "Foundation",
    "Win32_Foundation",
    "Win32_System_WinRT",
]
version = "0.52.0"
